-- AlterTable
ALTER TABLE `QueHacerActivity` ADD COLUMN `tagline` VARCHAR(500) NULL,
    ADD COLUMN `introMarkdown` TEXT NULL,
    ADD COLUMN `accentHsl` VARCHAR(64) NULL,
    ADD COLUMN `listingMode` ENUM('DESTINATIONS', 'BIODIVERSITY', 'EXPERIENCES') NOT NULL DEFAULT 'DESTINATIONS';